# Change these first
owner: server-KaTys # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Apache @ KaTys
    url: https://katys.cf
    expectedStatusCodes:
      - 200
  - name: Tiana Lemesle @ KaKi87
    url: https://tianalemesle.fr
    expectedStatusCodes:
      - 200
  - name: Shields @ KaKi87
    url: https://shields.kaki87.net
    expectedStatusCodes:
      - 404
  - name: Gitea @ KaKi87
    url: https://git.kaki87.net
    expectedStatusCodes:
      - 200
  - name: Play Search @ KaKi87
    url: https://api.playsearch.kaki87.net
    expectedStatusCodes:
      - 404
  - name: Unrestrict @ KaKi87
    url: https://unrestrict.kaki87.net/
    expectedStatusCodes:
      - 200
  - name: LibreSpeed @ KaKi87
    url: https://speedtest.kaki87.net/
    expectedStatusCodes:
      - 200
  - name: General API @ KaKi87
    url: https://api.kaki87.net
    expectedStatusCodes:
      - 404
  - name: CestLaGreve API @ KaKi87
    url: https://cestlagreve.api.kaki87.net
    expectedStatusCodes:
      - 204
  - name: SSHception @ KaKi87
    url: kaki87.net
    port: 3100
    check: "tcp-ping"
  - name: SSHception web @ KaKi87
    url: https://ssh.kaki87.net
    expectedStatusCodes:
      - 200
  - name: cv.vg dev API @ KaKi87
    url: https://d.cv.vg
    expectedStatusCodes:
      - 200
  - name: Tolgee @ KaKi87
    url: https://i18n.kaki87.net
    expectedStatusCodes:
      - 200
  - name: Netdata @ KaTys
    url: https://netdata.katys.cf
    expectedStatusCodes:
      - 200
  - name: Glitchgit @ KaKi87
    url: https://glitchgit.kaki87.net
    expectedStatusCodes:
      - 204

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.katys.cf
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KaTys status
  introTitle: "**KaTys** server status"
  introMessage: This page shows the status of the services hosted on the KaTys server.
  navbar:
    - title: Status
      href: /
    - title: About
      href: https://katys.cf
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - KaKi87
