# Change these first
owner: server-KaTys # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: '[Tiana Lemesle] Portfolio'
    url: https://tianalemesle.fr
    expectedStatusCodes:
      - 200
  - name: '[KaKi87] Shields'
    url: https://shields.kaki87.net
    expectedStatusCodes:
      - 404
  - name: '[KaKi87] Git'
    url: https://git.kaki87.net
    expectedStatusCodes:
      - 200
  - name: '[KaKi87] Git - SSH'
    check: tcp-ping
    url: git.kaki87.net
    port: 3021
  - name: '[KaKi87] Play Search'
    url: https://api.playsearch.kaki87.net
    expectedStatusCodes:
      - 404
  - name: '[KaKi87] General API'
    url: https://api.kaki87.net
    expectedStatusCodes:
      - 301
    maxRedirects: 0
  - name: '[KaKi87] CestLaGreve API'
    url: https://cestlagreve.api.kaki87.net
    expectedStatusCodes:
      - 204
  - name: '[cv.vg] Dev API'
    url: https://d.cv.vg
    expectedStatusCodes:
      - 200
  - name: 'Dashboard'
    url: https://dashboard.katys.eu.org
    expectedStatusCodes:
      - 200
  - name: '[KaKi87] Sentry'
    url: https://sentry.kaki87.net
    expectedStatusCodes:
      - 200
  - name: 'Apache'
    url: https://37.187.135.104
    expectedStatusCodes:
      - 200
    __dangerous__insecure: true
  - name: '[KaKi87] Chat (Matrix)'
    url: https://federationtester.matrix.org/api/report?server_name=chat.kaki87.net
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"FederationOK": true'
  - name: '[KaKi87] Tauri updates'
    url: https://tauri-updates.kaki87.net
    expectedStatusCodes:
      - 404
  - name: '[KaKi87] Analytics'
    url: https://analytics.kaki87.net
    expectedStatusCodes:
      - 200
  - name: '[KaKi87] Subtitle Search'
    url: https://api.subtitle-search.kaki87.net
    expectedStatusCodes:
      - 404
  - name: '[KaKi87] Invite Tracker - Discord bot'
    url: https://discord.com/api/guilds/1184503220060573746/widget.json
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"username":"Invite Tracker"'
  - name: '[KaKi87] Warez - Discord bot'
    url: $PRIVATE_DISCORD_URL
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"username":"Warez"'
  - name: '[KaKi87] Warez Download API'
    url: https://wzdl.kaki87.net
  - name: '[KaKi87] Private service #2 - App'
    url: $PRIVATE_SERVICE_2_URL
    expectedStatusCodes:
      - 200
  - name: '[KaKi87] Downloads'
    url: https://dl.kaki87.net
    expectedStatusCodes:
      - 200
  - name: '[KaKi87] Mail - SMTP (port 25)'
    check: tcp-ping
    url: kaki87.net
    port: 25
  - name: '[KaKi87] Mail - SMTP (port 465)'
    check: tcp-ping
    url: kaki87.net
    port: 465
  - name: '[KaKi87] Mail - SMTP (port 587)'
    check: tcp-ping
    url: kaki87.net
    port: 587
  - name: '[KaKi87] Mail - IMAP'
    check: tcp-ping
    url: kaki87.net
    port: 993
  - name: '[KaKi87] Changedetection'
    url: https://changedetection.kaki87.net
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.katys.eu.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KaTys status
  introTitle: "**KaTys** server status"
  introMessage: This page shows the status of the services hosted on the KaTys server.
  navbar:
    - title: Status
      href: /
    - title: About
      href: https://katys.eu.org
    - title: Dashboard
      href: https://dashboard.katys.eu.org
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - KaKi87
