# Change these first
owner: server-KaTys # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: 'Portfolio'
    url: https://tianalemesle.fr
    expectedStatusCodes:
      - 200
  - name: 'Shields'
    url: https://shields.kaki87.net
    expectedStatusCodes:
      - 404
  - name: 'Git'
    url: https://git.kaki87.net
    expectedStatusCodes:
      - 200
  - name: 'Git - SSH'
    check: tcp-ping
    url: git.kaki87.net
    port: 3021
  - name: 'Play Search'
    url: https://api.playsearch.kaki87.net
    expectedStatusCodes:
      - 404
  - name: 'General API'
    url: https://api.kaki87.net
    expectedStatusCodes:
      - 301
    maxRedirects: 0
  - name: 'CestLaGreve API'
    url: https://cestlagreve.api.kaki87.net
    expectedStatusCodes:
      - 204
  - name: 'Dashboard'
    url: https://dashboard.kaki87.net
    expectedStatusCodes:
      - 200
  - name: 'Caddy'
    check: tcp-ping
    url: 185.16.61.203
    port: 443
  - name: 'Invite Tracker - Discord bot'
    url: https://discord.com/api/guilds/1184503220060573746/widget.json
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"username":"Invite Tracker"'
  - name: 'Warez - Discord bot'
    url: $DISCORD_WAREZ_MONITORING_GUILD_URL
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"username":"Warez"'
  - name: 'Warez Download API'
    url: https://wzdl.kaki87.net
  - name: 'Private service #2 - App'
    url: $PRIVATE_SERVICE_2_URL
    expectedStatusCodes:
      - 200
  - name: 'Downloads'
    url: https://dl.kaki87.net
    expectedStatusCodes:
      - 200
  - name: 'Mail - SMTP (port 25)'
    check: tcp-ping
    url: kaki87.net
    port: 25
  - name: 'Mail - SMTP (port 465)'
    check: tcp-ping
    url: kaki87.net
    port: 465
  - name: 'Mail - SMTP (port 587)'
    check: tcp-ping
    url: kaki87.net
    port: 587
  - name: 'Mail - IMAP (port 993)'
    check: tcp-ping
    url: kaki87.net
    port: 993
  - name: 'Changedetection'
    url: https://changedetection.kaki87.net
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kaki87.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KaTys status
  introTitle: "**KaTys** server status"
  introMessage: This page shows the status of the services hosted on the KaTys server.
  navbar:
    - title: Status
      href: /
    - title: About
      href: https://kaki87.net
    - title: Dashboard
      href: https://dashboard.kaki87.net
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - KaKi87
