# Change these first
owner: server-KaTys # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portfolio @ Tiana Lemesle
    url: https://tianalemesle.fr
    expectedStatusCodes:
      - 200
  - name: Shields @ KaKi87
    url: https://shields.kaki87.net
    expectedStatusCodes:
      - 404
  - name: Gitea @ KaKi87
    url: https://git.kaki87.net
    expectedStatusCodes:
      - 200
  - name: Play Search @ KaKi87
    url: https://api.playsearch.kaki87.net
    expectedStatusCodes:
      - 404
  - name: General API @ KaKi87
    url: https://api.kaki87.net
    expectedStatusCodes:
      - 404
  - name: CestLaGreve API @ KaKi87
    url: https://cestlagreve.api.kaki87.net
    expectedStatusCodes:
      - 204
  - name: Dev API @ cv.vg
    url: https://d.cv.vg
    expectedStatusCodes:
      - 200
  - name: Netdata
    url: https://netdata.katys.cf
    expectedStatusCodes:
      - 200
  - name: Glitchgit @ KaKi87
    url: https://glitchgit.kaki87.net
    expectedStatusCodes:
      - 204
  - name: Apache
    url: https://37.187.135.104
    expectedStatusCodes:
      - 200
    __dangerous__insecure: true
  - name: Chat (Matrix) @ KaKi87
    url: https://chat.kaki87.net/_matrix/client/versions
    expectedStatusCodes:
      - 200
  - name: Tauri update server @ KaKi87
    url: https://tauri-updates.kaki87.net
    expectedStatusCodes:
      - 404
  - name: Analytics @ KaKi87
    url: https://analytics.kaki87.net
    expectedStatusCodes:
      - 200
  - name: Subtitle Search @ KaKi87
    url: https://api.subtitle-search.kaki87.net
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.katys.cf
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KaTys status
  introTitle: "**KaTys** server status"
  introMessage: This page shows the status of the services hosted on the KaTys server.
  navbar:
    - title: Status
      href: /
    - title: About
      href: https://katys.cf
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - KaKi87
